#! /bin/bash

#Check if Parameters are set
if [ "$1" = "" ] || [ "$1" = "-h" ]; then
  echo "Welcome to get-waterfox 1.0!"
  echo ""
  echo "Usage:"
  echo "# get-waterfox init"
  echo "$ get-waterfox download"
  echo "# get-waterfox install"
  echo "$ get-waterfox update"
  echo "# get-waterfox remove"
  echo ""
  echo "Use '-h' to show this help"
  echo "Please run the commands this way: init; download; install"
  echo ""
  exit
fi

#Init Waterfox
if [ "$1" = "init" ]; then
if [ "$EUID" != "0" ]; then 
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[INIT] Creating folder /usr/share/waterfox"
  mkdir /usr/share/waterfox
  chmod 777 /usr/share/waterfox --recursive
  exit
fi

#Download Waterfox
if [ "$1" = "download" ]; then
  echo "[INFO] Downloading Waterfox from GitHub to /usr/share/waterfox"
  echo "[INFO] Please stand by ..."
  wget https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-$(curl -s https://api.github.com/repos/MrAlex94/Waterfox/releases/latest | grep tag_name | cut -d '"' -f 4).en-US.linux-x86_64.tar.bz2 -o /usr/share/waterfox/waterfox.tar.bz2
  echo "[ OK ] Now execute: sudo get-waterfox install"
  exit
fi

#Install Waterfox
if [ "$1" = "install" ]; then
  if [ "$EUID" != "0" ]; then 
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[INSTALLING] $(ls /usr/share/waterfox |grep .tar)"
  echo "[EXTRACTING] Please wait ..."
  tar -xf /usr/share/waterfox/waterfox.tar.bz2 /usr/share/waterfox/
  echo "[CLEAN] Cleaning up ..."
  rm /usr/share/waterfox.tar.bz2
  echo "[LINKING] Creating symlinks ..."
  ln -s /usr/share/waterfox/waterfox /bin/waterfox
  exit
fi


#Unkown Input
echo "Can't understand"
