#! /bin/bash

#Check if Parameters are set
if [ "$1" = "" ] || [ "$1" = "-h" ]; then
  echo "Welcome to get-waterfox 1.0!"
  echo ""
  echo "Usage:"
  echo ""
  echo "Create Waterfox dir:"
  echo "# get-waterfox init"
  echo ""
  echo "First installation"
  echo "$ get-waterfox download"
  echo "# get-waterfox install"
  echo ""
  echo "General commands"
  echo "# get-waterfox update"
  echo "$ get-waterfox cleanup"
  echo ""
  echo "Remove Waterfox"
  echo "# get-waterfox remove"
  echo ""
  echo "Use '-h' to show this help"
  echo "Please run the commands this way: init; download; install"
  exit
fi

#Init Waterfox
if [ "$1" = "init" ]; then
if [ "$EUID" != "0" ]; then 
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[INIT] Creating folder /usr/share/waterfox"
  mkdir /usr/share/waterfox
  echo "[INIT] Alter rights in /usr/share/waterfox to 776"
  chmod 776 /usr/share/waterfox --recursive
  exit
fi

#Download Waterfox
if [ "$1" = "download" ]; then
  if [ -e "/usr/share/waterfox/waterfox.tar.bz2" ]; then
    echo "[CLEAN] Cleaning up ..."
    rm /usr/share/waterfox/waterfox.tar.bz2
  else 
    echo "[INFO] Cache is already clean!"
  fi 
  echo "[INFO] Downloading current Waterfox from waterfoxproject.org to /usr/share/waterfox"
  echo "[INFO] Please stand by ..."
  #wget https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-$(curl -s https://api.github.com/repos/MrAlex94/Waterfox/releases/latest | grep tag_name | cut -d '"' -f 4).en-US.linux-x86_64.tar.bz2 -O /usr/share/waterfox/waterfox.tar.bz2
  wget $(curl https://waterfoxproject.org/en-US/ |grep -Eo "(https)://[a-zA-Z0-9./?=_-]*" |sort |grep linux64 |uniq) -O /usr/share/waterfox/waterfox.tar.bz2
  echo "[ OK ] Now execute: sudo get-waterfox install"
  exit
fi

#Install Waterfox
if [ "$1" = "install" ]; then
  if [ "$EUID" != "0" ]; then 
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[INSTALLING] $(ls /usr/share/waterfox |grep .tar)"
  echo "[EXTRACTING] Please wait ..."
  tar -xf /usr/share/waterfox/waterfox.tar.bz2 -C /usr/share/waterfox/
  echo "[LINKING] Creating symlinks ..."
  ln -s /usr/share/waterfox/waterfox/waterfox /bin/waterfox
  echo "[LINKING] Creating starter in /usr/share/applications"
  touch /usr/share/applications/waterfox.desktop
  echo "[Desktop Entry]" > /usr/share/applications/waterfox.desktop
  echo "Version=1.0" >> /usr/share/applications/waterfox.desktop
  echo "Encoding=UTF-8" >> /usr/share/applications/waterfox.desktop
  echo "Name=Waterfox" >> /usr/share/applications/waterfox.desktop
  echo "Comment=Browse the World Wide Web" >> /usr/share/applications/waterfox.desktop
  echo "GenericName=Web Browser" >> /usr/share/applications/waterfox.desktop
  echo "Keywords=Internet;WWW;Browser;Web;Explorer" >> /usr/share/applications/waterfox.desktop
  echo "Exec=waterfox %u" >> /usr/share/applications/waterfox.desktop
  echo "Terminal=false" >> /usr/share/applications/waterfox.desktop
  echo "X-MuiltpleArgs=false" >> /usr/share/applications/waterfox.desktop
  echo "Type=Application" >> /usr/share/applications/waterfox.desktop
  echo "Icon=/usr/share/waterfox/waterfox/browser/icons/mozicon128.png" >> /usr/share/applications/waterfox.desktop
  echo "Categories=Network;WebBrowser;" >> /usr/share/applications/waterfox.desktop
  echo "MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;" >> /usr/share/applications/waterfox.desktop
  echo "StartupWMClass=Waterfox" >> /usr/share/applications/waterfox.desktop
  echo "StartupNotify=true" >> /usr/share/applications/waterfox.desktop
  echo "Actions=NewWindow;NewPrivateWindow;" >> /usr/share/applications/waterfox.desktop
  echo "" >> /usr/share/applications/waterfox.desktop
  echo "[Desktop Action NewWindow]" >> /usr/share/applications/waterfox.desktop
  echo "Name=Open a New Window" >> /usr/share/applications/waterfox.desktop
  echo "Exec=waterfox -new-window" >> /usr/share/applications/waterfox.desktop
  echo "" >> /usr/share/applications/waterfox.desktop
  echo "[Desktop Action NewPrivateWindow]" >> /usr/share/applications/waterfox.desktop
  echo "Name=Open a New Private Window" >> /usr/share/applications/waterfox.desktop
  echo "Exec=waterfox -private-window" >> /usr/share/applications/waterfox.desktop
  echo ""
  echo "[INFO] Installation done!"
  echo "[WARN] A cache copy of the Waterfox tarball still exist!"
  echo "[INFO] You can clean the cache now by running: 'sudo get-waterfox cleanup'"
  echo "[INFO] Otherweise you can allways use 'get-waterfox download' to overwrite the old cache copy with a new one."
  exit
fi

#Remove Waterfox
if [ "$1" = "remove" ]; then
if [ "$EUID" != "0" ]; then 
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[ALERT] Removing folder /usr/share/waterfox"
  rm -rf /usr/share/waterfox
  rm /usr/share/applications/waterfox.desktop
  unlink /bin/waterfox
  echo "[READY] Waterfox was completely removed from your System!"
  exit
fi

#Update Waterfox
if [ "$1" = "update" ]; then
if [ "$EUID" != "0" ]; then 
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[UPDATE] Updating Waterfox ..."
  echo "[PREP] Preparing /usr/share/waterfox ..."
  rm -rf /usr/share/waterfox/*
  echo "[INFO] Downloading current Waterfox from waterfoxproject.org to /usr/share/waterfox"
  echo "[INFO] Please stand by ..."
  wget $(curl https://waterfoxproject.org/en-US/ |grep -Eo "(https)://[a-zA-Z0-9./?=_-]*" |sort |grep linux64 |uniq) -O /usr/share/waterfox/waterfox.tar.bz2
  echo "[ OK ] Download ready!"
  echo "[EXTRACTING] Please wait ..."
  tar -xf /usr/share/waterfox/waterfox.tar.bz2 -C /usr/share/waterfox/
  echo "[CLEAN] Cleaning up ..."
  rm /usr/share/waterfox/waterfox.tar.bz2
  echo "[DONE] Update ready!"
  exit
fi

#Cleanup Waterfox
if [ "$1" = "cleanup" ]; then
  if [ -e "/usr/share/waterfox/waterfox.tar.bz2" ]; then
    echo "[CLEAN] Cleaning up ..."
    rm /usr/share/waterfox/waterfox.tar.bz2
  else 
    echo "[INFO] Cache is already clean!"
  fi 
  echo "[ OK ] Done!"
  exit
fi


#Unkown Input
echo "Can't understand, plsease use -h for help"
