#! /bin/bash

version="1.5.1"

#Check if Parameters are set
if [ "$1" = "" ] || [ "$1" = "-h" ]; then
  echo "Welcome to get-waterfox $version !"
  echo ""
  echo "Usage:"
  echo ""
  echo "Create Waterfox dir:"
  echo "# get-waterfox init >>> First init to create env >>> -I"
  echo ""
  echo "First installation"
  echo "$ get-waterfox download >>> Download the current Waterfox Tarball >>> -d"
  echo "# get-waterfox install >>> Install the Waterfox Tarball & create all links etc >>> -i"
  echo ""
  echo "General commands"
  echo "# get-waterfox update >>> Update Waterfox >>> -u"
  echo "$ get-waterfox cleanup >>> Delete old waterfox tarball >>> -C"
  echo "$ get-waterfox checkupdate >>> Shows if a Waterfox update is available >>> -c"
  echo "$ get-waterfox version >>> Print version of get-waterfox >>> -v"
  echo ""
  echo "Remove Waterfox"
  echo "# get-waterfox remove >>> Remove Waterfox complete >>> -r"
  echo ""
  echo "Use '-h' to show this help"
  echo "Please run the commands this way: init; download; install"
  exit
fi

#Init Waterfox
if [ "$1" = "init" ] || [ "$1" = "-I" ]; then
if [ "$EUID" != "0" ]; then
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[INIT] Creating working folder /usr/share/waterfox"
  mkdir /usr/share/waterfox
  echo "[INIT] Creating data folder /usr/share/waterfox"
  mkdir /usr/share/waterfox-data
  echo "[INIT] Alter rights in working & data dir"
  chmod 777 /usr/share/waterfox/ --recursive
  chmod 777 /usr/share/waterfox-data/ --recursive
  echo "[INIT] Creating localversion file"
  touch /usr/share/waterfox-data/localversion
  echo "[INIT] Alter rights for localversion file"
  chmod 777 /usr/share/waterfox-data/localversion
  exit
fi

#Download Waterfox
if [ "$1" = "download" ] || [ "$1" = "-d" ]; then
  if [ -e "/usr/share/waterfox-data/waterfox.tar.bz2" ]; then
    echo "[CLEAN] Cleaning up ..."
    rm /usr/share/waterfox-data/waterfox.tar.bz2
  else
    echo "[INFO] Cache is already clean!"
  fi
  echo "[INFO] Downloading current Waterfox from waterfoxproject.org to /usr/share/waterfox-data"
  remoteversion="$(curl https://www.waterfox.net/releases/ |grep -Eo "(https)://[a-zA-Z0-9./?=_-]*" |sort |grep linux64 |uniq |grep classic)"
  echo "[INFO] Please stand by ..."
  wget $remoteversion -O /usr/share/waterfox-data/waterfox.tar.bz2
  echo "[INFO] Download ready!"
  echo "[INFO] Setup localversion file"
  echo "[INFO] Updating localversion file"
  echo "$remoteversion" > /usr/share/waterfox-data/localversion
  echo "[ OK ] Now execute: sudo get-waterfox install"
  exit
fi

#Install Waterfox
if [ "$1" = "install" ] || [ "$1" = "-i" ]; then
  if [ "$EUID" != "0" ]; then
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[INSTALLING] $(ls /usr/share/waterfox-data/ |grep .tar)"
  echo "[EXTRACTING] Please wait ..."
  tar -xf /usr/share/waterfox-data/waterfox.tar.bz2 -C /usr/share/waterfox/
  echo "[LINKING] Creating symlinks ..."
  ln -s /usr/share/waterfox/waterfox-classic/waterfox /bin/waterfox
  echo "[LINKING] Creating starter in /usr/share/applications"
  touch /usr/share/applications/waterfox.desktop
  echo "[Desktop Entry]" > /usr/share/applications/waterfox.desktop
  echo "Version=1.0" >> /usr/share/applications/waterfox.desktop
  echo "Encoding=UTF-8" >> /usr/share/applications/waterfox.desktop
  echo "Name=Waterfox" >> /usr/share/applications/waterfox.desktop
  echo "Comment=Browse the World Wide Web" >> /usr/share/applications/waterfox.desktop
  echo "GenericName=Web Browser" >> /usr/share/applications/waterfox.desktop
  echo "Keywords=Internet;WWW;Browser;Web;Explorer" >> /usr/share/applications/waterfox.desktop
  echo "Exec=waterfox %u" >> /usr/share/applications/waterfox.desktop
  echo "Terminal=false" >> /usr/share/applications/waterfox.desktop
  echo "X-MuiltpleArgs=false" >> /usr/share/applications/waterfox.desktop
  echo "Type=Application" >> /usr/share/applications/waterfox.desktop
  echo "Icon=/usr/share/waterfox/waterfox-classic/browser/chrome/icons/default/default128.png" >> /usr/share/applications/waterfox.desktop
  echo "Categories=Network;WebBrowser;" >> /usr/share/applications/waterfox.desktop
  echo "MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;" >> /usr/share/applications/waterfox.desktop
  echo "StartupWMClass=Waterfox" >> /usr/share/applications/waterfox.desktop
  echo "StartupNotify=true" >> /usr/share/applications/waterfox.desktop
  echo "Actions=NewWindow;NewPrivateWindow;" >> /usr/share/applications/waterfox.desktop
  echo "" >> /usr/share/applications/waterfox.desktop
  echo "[Desktop Action NewWindow]" >> /usr/share/applications/waterfox.desktop
  echo "Name=Open a New Window" >> /usr/share/applications/waterfox.desktop
  echo "Exec=waterfox -new-window" >> /usr/share/applications/waterfox.desktop
  echo "" >> /usr/share/applications/waterfox.desktop
  echo "[Desktop Action NewPrivateWindow]" >> /usr/share/applications/waterfox.desktop
  echo "Name=Open a New Private Window" >> /usr/share/applications/waterfox.desktop
  echo "Exec=waterfox -private-window" >> /usr/share/applications/waterfox.desktop
  echo ""
  echo ""
  echo "[INFO] Installation done!"
  echo "[WARN] A cache copy of the Waterfox tarball still exist!"
  echo "[INFO] You can clean the cache now by running: 'sudo get-waterfox cleanup'"
  echo "[INFO] Otherweise you can allways use 'get-waterfox download' to overwrite the old cache copy with a new one."
  exit
fi

#Remove Waterfox
if [ "$1" = "remove" ] || [ "$1" = "-r" ]; then
if [ "$EUID" != "0" ]; then
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[ALERT] Removing folder /usr/share/waterfox"
  rm -rf /usr/share/waterfox
  echo "[ALERT] Removing folder /usr/share/waterfox-data"
  rm -rf /usr/share/waterfox-data
  echo "[ALERT] Removing starter from /usr/share/applications"
  rm /usr/share/applications/waterfox.desktop
  echo "[ALERT] Removing symlinks"
  unlink /bin/waterfox
  echo "[READY] Waterfox was completely removed from your System!"
  exit
fi

#Update Waterfox
if [ "$1" = "update" ] || [ "$1" = "-u" ]; then
  if [ "$EUID" != "0" ]; then
    echo "[INFO] Please run as root"
    exit
  fi
  echo "[UPDATE] Waterfox update started!"
  echo "[INFO] Searching for new version ..."
  echo "[INFO] Checking localversion file ..."
  localversion="$(cat /usr/share/waterfox-data/localversion)"
  echo "[INFO] Checking remote version(s) ..."
  remoteversion="$(curl https://www.waterfox.net/releases/ |grep -Eo "(https)://[a-zA-Z0-9./?=_-]*" |sort |grep linux64 |uniq |grep classic)"
  if [ "$localversion" == "$remoteversion" ]; then
    echo "[INFO] The latest version is already installed!"
    exit
  fi
  echo "[INFO] New version found!"
  echo "[PREP] Preparing /usr/share/waterfox ..."
  rm -rf /usr/share/waterfox/*
  echo "[PREP] Preparing /usr/share/waterfox-data ..."
  rm -rf /usr/share/waterfox-data/waterfox.tar.bz2
  echo "[INFO] Downloading current Waterfox from waterfoxproject.org to /usr/share/waterfox-data"
  echo "[INFO] Please stand by ..."
  wget $remoteversion -O /usr/share/waterfox-data/waterfox.tar.bz2
  echo "[ OK ] Download ready!"
  echo "[EXTRACTING] Please wait ..."
  tar -xf /usr/share/waterfox-data/waterfox.tar.bz2 -C /usr/share/waterfox/
  echo "[INFO] Updating localversion file"
  echo "$remoteversion" > /usr/share/waterfox-data/localversion
  echo "[DONE] Update ready!"
  echo "[WARN] A cache copy of the Waterfox tarball still exist!"
  echo "[INFO] You can clean the cache now by running: 'sudo get-waterfox cleanup'"
  echo "[INFO] Otherweise you can allways use 'get-waterfox download' to overwrite the old cache copy with a new one."
  exit
fi

#Cleanup Waterfox
if [ "$1" = "cleanup" ] || [ "$1" = "-C" ]; then
  if [ -e "/usr/share/waterfox/waterfox.tar.bz2" ]; then
    echo "[CLEAN] Cleaning up ..."
    rm /usr/share/waterfox-data/waterfox.tar.bz2
  else
    echo "[INFO] Cache is already clean!"
  fi
  echo "[ OK ] Done!"
  exit
fi

#Checkupdate
if [ "$1" = "checkupdate" ] || [ "$1" = "-c" ]; then
  echo "[INFO] Searching for new version of Waterfox ..."
  echo "[INFO] Checking localversion file ..."
  localversion="$(cat /usr/share/waterfox-data/localversion)"
  echo "[INFO] Checking remote version(s) ..."
  remoteversion="$(curl https://www.waterfox.net/releases/ |grep -Eo "(https)://[a-zA-Z0-9./?=_-]*" |sort |grep linux64 |uniq |grep classic)"
  if [ "$localversion" == "$remoteversion" ]; then
    echo "[INFO] The latest version is already installed!"
    exit
  fi
  echo "[INFO] New version found!"
  echo "[INFO] You can update your Waterfox by running: sudo get-waterfox update"
  exit
fi

#Version
if [ "$1" = "version" ] || [ "$1" = "-v" ]; then
  echo "get-waterfox $version"
  exit
fi


#Unkown Input
echo "Can't understand, plsease use -h for help"
